/* eslint-disable prettier/prettier */
export default {
   username: 'Usuario',
   password: 'Clave',
   login: 'Login',
   welcome: 'Bienvenido',
   change_language: 'Cambia idioma',
   Tabs: 'Inicio',

   Lista_instalaciones: 'Instalaciones',
   Maintenance: 'Mantenimiento',
   DetallesInstalacion: 'Detalles Instación',
   Grabar: 'Grabar',
   EstadoStore: 'Estado store',
   Nodata: 'No hay datos',
   DosimacRegistration: 'Alta Dosimac',
   NewDmMaternity: 'Nuevo Dosimac maternidad',
   DosimacG: 'Dosimac-G',
   DosimacI: 'Dosimac-I',
   UpdDmMaternity: 'Cambio Dosimac maternidad',
   NewDmGestation: 'Nuevo Dosimac gestación',
   UpdDmGestation: 'Cambio dosimac gestación',
   StartScan: 'Buscar equipos DOSIMAC',
   DosimacList: 'Equipos DOSIMAC',
   PressToScan: 'Pulse',
   DosimacSetup: 'Configuracion',
   TestoPresioneAlta: "Presione sobre el boton para buscar dispositivos",
   Instalación_seleccionada: "Instalación seleccionada",
   NoInstalacionSeleccionada: "No hay instalación seleccionada",
   BorrarGranja: "Borrar granja",
   Deseaborrarlagranja: "¿Desea borrar la granja?",
   Guardar: 'Guardar',
   Cancelar: 'Cancelar',
   Aceptar: 'Aceptar',
   NombreGranja: 'Farm name',
   Localidad: 'Location',
   Provincia: 'Province',
   NombreWifi: 'Wifi SSID',
   PasswordWifi: 'Wifi password',
   No_hay_dispositivos: 'No hay dispositivos',
   Aviso: 'Aviso',
   SearchingDevicesº: 'Buscando equipos...',
   NoSePuedeBorrarGranja: "No se puede borrar una granja nueva",
   settings: 'Ajustes',
   softwareVersion: "software Version"


};